config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :builds
  root  'builds#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
    has_one :character
    has_many :talents
    has_many :comments
    has_many :skills
end

app/models/character.rb
class Character < ApplicationRecord
    belongs_to :build, required: false
    has_many :skills
    has_many :talents
    def name_with_initial
        "#{name}"
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :build
end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :build, required: false
    belongs_to :character, required: false
end

app/models/talent.rb
class Talent < ApplicationRecord
    belongs_to :build, required: false
    belongs_to :character, required: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]

  # GET /builds
  # GET /builds.json
  def index
    @builds = Build.all
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  # GET /builds/new
  def new
    @build = Build.new
  end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(build_params)
    @build.user_id = current_user.id
    @build.character_id = params[:character][:character_id]
    
    respond_to do |format|
      if @build.save
        format.html { redirect_to @build, notice: 'Build was successfully created.' }
        format.json { render :show, status: :created, location: @build }
      else
        format.html { render :new }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builds/1
  # PATCH/PUT /builds/1.json
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { render :show, status: :ok, location: @build }
      else
        format.html { render :edit }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url, notice: 'Build was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:title, :description, :character)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/builds/_form.html.erb
<%= form_with(model: build, local: true) do |form| %>
  <% if build.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% build.errors.full_messages.each do |message| %>
        <li><%= message %></li> 
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container text-center">
    <%= collection_select(:character, :character_id, Character.all, :id, :name_with_initial, prompt: true) %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :build_title %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :build_description %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>

  </div>

app/views/builds/_user_session.html.erb
<% if user_signed_in? %>
    <%= link_to 'New Build', new_build_path %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

<% else %>
    <%= link_to 'Sign in', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/builds/edit.html.erb
<div class="container panel panel-default text-center">
  <h1>Editing Build</h1>

  <%= render 'form', build: @build %>

  <%= link_to 'Show', @build %> |
  <%= link_to 'Back', builds_path %>

</div>

app/views/builds/index.html.erb
<div class="container">
    <div class="jumbotron">
      <div id="heroesRotation">
        <table>
          <tr>
            <td><img id="heroesPortrait" src="heroes_portraits/kaelthas.png" alt=""></td>
            <td><img id="heroesPortrait" src="heroes_portraits/thrall.png" alt=""></td>
            <td><img id="heroesPortrait" src="heroes_portraits/kaelthas.png" alt=""></td>
            <td><img id="heroesPortrait" src="heroes_portraits/thrall.png" alt=""></td>
            <td><img id="heroesPortrait" src="heroes_portraits/kaelthas.png" alt=""></td>
          </tr>
          <tr>
            <td><img id="heroesPortrait" src="heroes_portraits/leoric.png" alt=""></td>
            <td><img id="heroesPortrait" src="heroes_portraits/varian.png" alt=""></td>
            <td><img id="heroesPortrait" src="heroes_portraits/leoric.png" alt=""></td>
            <td><img id="heroesPortrait" src="heroes_portraits/varian.png" alt=""></td>
            <td><img id="heroesPortrait" src="heroes_portraits/leoric.png" alt=""></td>
          </tr>
        </table>
      </div>
    <!-- <h1>HOTS</h1> -->
</div>

</div>


<div class="container panel panel-default text-center">
  <h1>Builds</h1>
  <p id="notice"><%= notice %></p>
  <table class="table text-center">
    <thead class="thead-inverse">
      <tr>
          <th>Herói</th>
          <th>Título</th>
          <th>Descrição</th>
          <th colspan="3"></th>
      </tr>
    </thead>

        <tbody>
          <% @builds.each do |build| %>
            <tr>
              <td><%= Character.find(build.character_id).name%></td>
              <td><%= build.title %></td>
              <td><%= build.description %></td>
              <td><%= link_to 'Show', build %></td>
              <% if current_user != nil %>
                  <% if current_user.id == build.user_id %>
                      <td><%= link_to 'Edit', edit_build_path(build) %></td>
                      <td><%= link_to 'Destroy', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% end %>
              <% end %>
            </tr>
          <% end %>
        </tbody>
  </table>

  <br>

</div>

app/views/builds/new.html.erb
<div class="container panel panel-default text-center">
  <h1>Nova Build</h1>

  <%= render 'form', build: @build %>

  <%= link_to 'Back', builds_path %>

</div>

app/views/builds/show.html.erb
<div class="container panel panel-default text-center">
  <p id="notice"><%= notice %></p>

  <p>
      <strong>Herói:</strong>
      <%= Character.find(@build.character_id).name %>
  </p>

  <p>
    <strong>Título:</strong>
    <%= @build.title %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= @build.description %>
  </p>

  <%= link_to 'Edit', edit_build_path(@build) %> |
  <%= link_to 'Back', builds_path %>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :comment_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_user_session.html.erb
<div class="container">
  <% if user_signed_in? %>
      <%= link_to 'New Build', new_build_path %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

  <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotsBrasil</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <div class="page-header text-center">
        <%=link_to image_tag("hots_logo"),'/'%>
        <!-- <img src="hots_logo.png" alt="logo" /> -->
      </div>
    </div>

    <div class="container">
      <nav class="navbar navbar-inverse">
      <div class="container-fluid">
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%=link_to 'Home', '/'%></li>
          <li><a href="#">Notícias</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Guias de Herois <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Kael</a></li>
              <li><a href="#">Thrall</a></li>
              <li><a href="#">Leoric</a></li>
            </ul>
          </li>
          <li><a href="#">Builds</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if user_signed_in? %>
            <%= link_to 'New Build', new_build_path %>
            <% else %>
            <%= link_to 'Sign up', new_user_registration_path %>
            <% end %>
          </li>
          <li>
            <% if user_signed_in? %>
            <%= link_to 'Sign out', destroy_user_session_path,  :method => :delete  %>
            <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
            <% end %>
          </li>
        </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    </div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="js/bootstrap.min.js"></script>


    <%= yield %>
    <!-- <p class="notice"><%= notice %></p> -->
    <p class="alert"><%= alert %></p>
  </body>
</html>